package org.chertzer.getshorty.util;

import org.junit.Before;
import org.junit.Test;

/**
 * Created by chertzer on 7/21/16.
 */
public class URLMapTest {
    URLStore urls;
    @Before
    public void setUp() throws Exception {
        urls = URLMap.getInstance();
    }
    @Test
    public void testGetSetValidURL() {
        String netflixURL = "http://www.netflix.com";
        assert(netflixURL.equals(urls.getURL(urls.setURL(netflixURL))));
    }
    @Test
    public void testGetSetInvalidURL() {
        String badSyntaxURL = "http://www.net flix.com";
        assert(badSyntaxURL.equals(urls.getURL(urls.setURL(badSyntaxURL))));
    }
    @Test
    public void testReallyLongURL() {
        String reallyLongURL = "http://www.netflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflixnetflix.com";
        assert(reallyLongURL.equals(urls.getURL(urls.setURL(reallyLongURL))));
    }
}